log_name: smoke_test

ppo:
    gamma: 0.99
    lam: 0.95
    lr: 0.005
    lr_gamma: 0.995
    batch_size: 4
    steps_per_epoch: 44
    nb_optim_iters: 1
    clip_ratio: 0.1
    clip_decay: 0.998
    ent_weight: 0.01
    critic_weight: 0.5
    gradient_clip_val: 1
    model_params:
        fac_c_in: 7
        c_hidden: 16
        c_out: 16
        num_layers: 2
        layer_name: GraphConv
        edge_dim: 1
        heads: 1
    data_path: ./data/smoke_20_1/

ppo_trainer:
    max_epochs: 1
    accelerator: cpu
    devices: 1
    enable_checkpointing: true
    track_grad_norm: 2
